### PR TITLE
SMLHelper and JSON parsing

### PR DESCRIPTION
**Pull request by allaboutmike**
Add dependency to SMLHelper mod and created an In-Game menu for the mod.
Removed System.Text.Json and all its dependencies, and added Newtonsoft.Json which is bundled with the game.
Updated all JSON handling code as required.
Removed Config.txt.Template. Config file will be replaced by config.json and events.json which are created when the game if first run and populated by the menu defaults.

### CODE REVIEW

**Comment by Shop-kins** [comment]
image
dependency issue, oculus.newtonsoft.json resolves this

**Comment by Shop-kins** [comment]
the config file is now a bit awkward. if you have to run it to create the config.json and you cant populate the config.json without then closing the program. should probably have the template file back?

**Comment by allaboutmike** [comment]
I've updated the csproj file with the references that I used to get this to build. Not sure if it is going to clear the Oculus issue or not, but it was building for me.

I don't have a copy of the config file atm to create the template, but I can generate and add one later before this gets merged if that's what we want.

**Comment by Shop-kins** [comment]
redownloaded, redid all the dependencys and still get the issue
it might be because my publicised dlls are old?
but then i guess this wont work on old patch? tho i suppose i dont use the mod on old patch anymore
using Oculus.Newtonsoft.Json; still resolves the problem

**Pull request merged**
